development:
  url: <%= ENV['DEV_SOLR_URL'] || "http://127.0.0.1:8983/solr/aster-development" %>
test:
  url: <%= ENV['TEST_SOLR_URL'] || 'http://127.0.0.1:8985/solr/aster-test' %>
production:
   url: http://127.0.0.1:8983/solr/aster
